<?xml version="1.0"?>
<package format="3">
  <name>vehicle_status_obd</name>
  <version>0.1.0</version>
  <description>Publish vehicle velocity from OBD-II via python-OBD as geometry_msgs/TwistStamped</description>

  <maintainer email="mujin@todo.todo">mujin</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
